stages:
  - deploy

deploy_to_infinityfree:
  stage: deploy
  image: debian:stable-slim
  before_script:
    - apt-get update -qq && apt-get install -y lftp
  script:
    - echo "Iniciando deploy a InfinityFree..."
    - |
      lftp -c "set ftp:ssl-allow no; set ftp:use-chmod no; open -u ${FTP_USER},${FTP_PASS} ${FTP_HOST}; mirror -v -R --no-perms ./ htdocs --exclude .git* --exclude .gitlab-ci.yml --exclude config/config.ini"
  only:
    - main